### ISSUE TITLE
Hours array is not correct for a day in which we change to or from DST

### ISSUE THREAD

**Issue by julian-jelfs** [mattlewis92/calendar-utils#28]
In the screenshot below we can see that the second and third entries in the array actually represent the same period of time. This is because there is an extra hour caused by moving from British Summer time to GMT on the 27th of October.  This causes the day view to misbehave for days where we move between DST and normal. 

![image](https://user-images.githubusercontent.com/45937480/61065210-24247a80-a3fb-11e9-8a2f-ba80d31395dd.png)

**Comment by julian-jelfs** [comment]
FYI I believe that you can easily see the same issue looking at the demo for your angular calendar component (which I presume uses the same underlying code). https://mattlewis92.github.io/angular-calendar/#/kitchen-sink

If you navigate to October the 27th you will see that 1am appears twice. 

Similarly if you navigate to March 29th 2020, you will see that 1am is missing. 

I believe that this is most likely a manifestation of exactly the same problem. 

If you have the week starting on a sunday then this affects week view as well as day view.

**Comment by mattlewis92** [comment]
Hey, thanks for reporting this, it's a known issue due to how date-fns operates in your local browser time. What it's doing is technically correct (the times don't exist in reality, so it displays a very literal interpretation, from a computer perspective it's correct, but from a users perspective it looks weird). You can workaround it by forcing the calendar to operate in UTC mode by using moment, if you take a look at the stackblitz here you'll see how to do that: https://github.com/mattlewis92/angular-calendar/issues/964#issuecomment-489412718 Once date-fns has a UTC mode I can probably build a more robust solution into the calendar itself but until then, this is sadly the only workable solution I can offer.
